"""Add Section 3 (Helper Functions) to the notebook."""

import json

# Read existing notebook
with open("step3_code_review.ipynb", "r", encoding="utf-8") as f:
    notebook = json.load(f)

# Add Section 3 cells
section3_cells = [
    {
        "cell_type": "markdown",
        "id": "c3d4e5f6",
        "metadata": {},
        "source": [
            "## 3. Helper Functions\n",
            "Define reusable functions for filtering, label computation, and text preprocessing. Each function includes docstrings for documentation and type hints where appropriate."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": 3,
        "id": "d4e5f6g7",
        "metadata": {},
        "outputs": [
            {
                "name": "stdout",
                "output_type": "stream",
                "text": [
                    "Helper functions defined.\n"
                ]
            }
        ],
        "source": [
            "def is_physical_deliverable(psc_code: str) -> bool:\n",
            "    \"\"\"Check if a PSC code indicates physical deliverables.\n",
            "    \n",
            "    Physical deliverables include:\n",
            "    - Y-series: Construction of structures and facilities\n",
            "    - Z-series: Maintenance/repair/alteration of real property  \n",
            "    - 10-99 (numeric): Supplies and equipment\n",
            "    \n",
            "    Args:\n",
            "        psc_code: Product or Service Code from FPDS\n",
            "        \n",
            "    Returns:\n",
            "        True if PSC indicates physical deliverables, False otherwise\n",
            "    \"\"\"\n",
            "    if pd.isna(psc_code):\n",
            "        return False\n",
            "    \n",
            "    psc_str = str(psc_code).strip().upper()\n",
            "    \n",
            "    # Check for Y or Z series\n",
            "    if psc_str.startswith(('Y', 'Z')):\n",
            "        return True\n",
            "    \n",
            "    # Check for numeric range 10-99\n",
            "    try:\n",
            "        psc_num = int(psc_str)\n",
            "        return PHYSICAL_PSC_NUMERIC_RANGE[0] <= psc_num <= PHYSICAL_PSC_NUMERIC_RANGE[1]\n",
            "    except ValueError:\n",
            "        return False\n",
            "\n",
            "\n",
            "def compute_cost_growth(base_val: str, final_val: str) -> float:\n",
            "    \"\"\"Compute percentage cost growth between base and final values.\n",
            "    \n",
            "    Args:\n",
            "        base_val: Base contract value (string with dollar signs)\n",
            "        final_val: Final contract value (string with dollar signs)\n",
            "        \n",
            "    Returns:\n",
            "        Percentage growth (e.g., 0.15 for 15% growth)\n",
            "        Returns NaN if values are invalid or zero\n",
            "    \"\"\"\n",
            "    try:\n",
            "        # Clean dollar values (remove $ and commas)\n",
            "        base = float(str(base_val).replace('$', '').replace(',', '').strip())\n",
            "        final = float(str(final_val).replace('$', '').replace(',', '').strip())\n",
            "        \n",
            "        # Avoid division by zero\n",
            "        if base == 0:\n",
            "            return np.nan\n",
            "            \n",
            "        # Compute percentage growth\n",
            "        growth = (final - base) / base\n",
            "        return growth\n",
            "        \n",
            "    except (ValueError, TypeError):\n",
            "        return np.nan\n",
            "\n",
            "\n",
            "def compute_delay(current_date: str, ultimate_date: str) -> int:\n",
            "    \"\"\"Compute schedule delay in days between current and ultimate completion dates.\n",
            "    \n",
            "    Args:\n",
            "        current_date: Current completion date (YYYY-MM-DD string)\n",
            "        ultimate_date: Ultimate completion date (YYYY-MM-DD string)\n",
            "        \n",
            "    Returns:\n",
            "        Delay in days (positive = late, negative = early)\n",
            "        Returns NaN if dates are invalid\n",
            "    \"\"\"\n",
            "    try:\n",
            "        current = pd.to_datetime(current_date)\n",
            "        ultimate = pd.to_datetime(ultimate_date)\n",
            "        \n",
            "        # Compute difference in days\n",
            "        delay = (ultimate - current).days\n",
            "        return delay\n",
            "        \n",
            "    except (ValueError, TypeError):\n",
            "        return np.nan\n",
            "\n",
            "\n",
            "def clean_text(text: str) -> str:\n",
            "    \"\"\"Clean and normalize text for NLP processing.\n",
            "    \n",
            "    Performs:\n",
            "    - Lowercase conversion\n",
            "    - Removal of special characters and extra whitespace\n",
            "    - Tokenization\n",
            "    - Lemmatization using spaCy\n",
            "    - Stop word removal\n",
            "    \n",
            "    Args:\n",
            "        text: Raw text string\n",
            "        \n",
            "    Returns:\n",
            "        Cleaned, normalized text string\n",
            "    \"\"\"\n",
            "    if pd.isna(text) or not isinstance(text, str):\n",
            "        return \"\"\n",
            "    \n",
            "    # Basic cleaning\n",
            "    text = text.lower()\n",
            "    text = re.sub(r'[^a-z0-9\\s]', ' ', text)  # Remove special chars\n",
            "    text = re.sub(r'\\s+', ' ', text)  # Normalize whitespace\n",
            "    \n",
            "    # Process with spaCy\n",
            "    doc = nlp(text)\n",
            "    \n",
            "    # Filter tokens: keep word tokens, remove stop words and short tokens\n",
            "    tokens = [token.lemma_ for token in doc \n",
            "               if not token.is_stop \n",
            "               and not token.is_punct \n",
            "               and len(token.lemma_) > 2]\n",
            "    \n",
            "    return ' '.join(tokens)\n",
            "\n",
            "\n",
            "def tfidf_tokenize(text: str) -> str:\n",
            "    \"\"\"Tokenizer function for TF-IDF vectorizer.\n",
            "    \n",
            "    Simple tokenization without lemmatization for TF-IDF processing.\n",
            "    This preserves more surface forms for the bag-of-words approach.\n",
            "    \n",
            "    Args:\n",
            "        text: Input text string\n",
            "        \n",
            "    Returns:\n",
            "        Tokenized text string\n",
            "    \"\"\"\n",
            "    if pd.isna(text) or not isinstance(text, str):\n",
            "        return \"\"\n",
            "    \n",
            "    # Basic tokenization\n",
            "    tokens = text.lower().split()\n",
            "    # Remove short tokens and basic filtering\n",
            "    tokens = [t for t in tokens if len(t) > 2 and t.isalpha()]\n",
            "    return ' '.join(tokens)\n",
            "\n",
            "\n",
            "print(\"Helper functions defined.\")"
        ]
    }
]

# Append the new cells
notebook["cells"].extend(section3_cells)

# Write back
with open("step3_code_review.ipynb", "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)

print("✅ Section 3 (Helper Functions) added - 5 functions defined")
